name: Update HomePage Site

on: 
  push:
    branches:
      - master

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Catch
      uses: actions/cache@v1
      id: cache-dependencies
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Generate
      run: |
        yarn run build

    - name: Deploy
      run: |
        cd ./dist
        git init
        git config --global user.name "ccknbc"
        git config --global user.email '${{ secrets.GIT_EMAIL }}'
        git add .
        git commit -m "Update"
        git push --force --quiet "https://ccknbc:${{ secrets.GH_TOKEN }}@github.com/ccknbc/ccknbc.github.io" master:master
        git push --force --quiet "https://ccknbc:${{ secrets.GT_TOKEN }}@gitee.com/ccknbc/ccknbc" master:master
        git push --force --quiet "https://${{ secrets.CD_USER }}:${{ secrets.CD_TOKEN }}@e.coding.net/ccknbc/blog/home.git" master:master

    - name: Update Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: ccknbc
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ccknbc/ccknbc